# Generated by Django 5.0.4 on 2024-06-21 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('temperature', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-99), django.core.validators.MaxValueValidator(99)])),
                ('weather_description', models.CharField(max_length=255)),
            ],
        ),
    ]
